version: 2.1

jobs:
  'awesome-bot':
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: gem install awesome_bot
      - run: awesome_bot README.md --allow-redirect --allow-dupe
  'awesome-lint':
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run: yarn add awesome-lint
      - save_cache:
          paths:
            - ~/.cache/yarn
      - run: yarn awesome-lint

workflows:
  version: 2
  build:
    jobs:
      - 'awesome-lint'
      - 'awesome-bot'
